export const siteRoutes = [
  { path: "/", name: "Home" },
  { path: "/services", name: "Services" },
  { path: "/projects", name: "Projects" },
  { path: "/about-us", name: "About Us" },
  { path: "/contact-us", name: "Contact Us" },
  { path: "/events", name: "Events" },
  { path: "/blog", name: "Blog" },
  { path: "/seating", name: "Seating" },
  { path: "/desking-and-tables", name: "Desking & Tables" },
  { path: "/categories/storage", name: "Storage" },
  { path: "/breakout-pods", name: "Breakout & Pods" },
  { path: "/ergonomics-and-acoustics", name: "Ergonomics & Acoustics" },
  { path: "/lighting-accessories", name: "Lighting & Accessories" },
  { path: "/reception-health", name: "Reception / Health" },
  { path: "/home-office-furniture", name: "Home Office Furniture" },
  { path: "/ernest-race-heritage-collection", name: "Ernest Race Heritage Collection" },
  { path: "/pods-booths", name: "Pods & Booths" },
  { path: "/wonderfully-quirky", name: "Wonderfully Quirky" },
  { path: "/jean-prouve-collection", name: "Jean Prouvé Collection" },
  { path: "/whiteboards", name: "Whiteboards" },
  { path: "/reddot-design-award-winners", name: "Reddot Design Award Winners" },
  { path: "/categories/Furniture-for-the-Home", name: "Furniture for the Home" },
  { path: "/clearance", name: "Clearance" },
  { path: "/meeting-room", name: "Meeting Room" },
  { path: "/reception", name: "Reception" },
  { path: "/breakout-space", name: "Breakout Space" },
  { path: "/canteen", name: "Canteen" },
  { path: "/traditional-work", name: "Traditional Work" },
  { path: "/focused-work", name: "Focused Work" },
  { path: "/hybrid-work", name: "Hybrid Work" },
  { path: "/collaborative-space", name: "Collaborative Space" },
  { path: "/training-room", name: "Training Room" },
  { path: "/inspiration-by-sector-education", name: "Education" },
  { path: "/inspiration-by-sector-hospitality", name: "Hospitality" },
  { path: "/inspiration-by-sector-financial", name: "Financial / Legal" },
  { path: "/inspiration-by-sector-media-technology", name: "Media / Technology" },
  { path: "/inspiration-by-sector-design", name: "Design" },
  { path: "/inspiration-by-sector-healthcare", name: "Healthcare" },
  { path: "/inspiration-by-sector-coworking", name: "Coworking" },
  { path: "/inspiration-by-sector-airports-transportation", name: "Airports / Transportation" },
  { path: "/inspiration-by-sector-entertainment-stadia", name: "Entertainment / Stadia" },
  { path: "/inspiration-by-sector-charity", name: "Charity" },
  { path: "/inspiration-by-sector-manufacturing", name: "Manufacturing" },
];
